# Generated by Django 5.2.4 on 2025-07-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
